// _GPGCompatibilityPrefs_EOArchive_Spanish.java
// Generated by EnterpriseObjects palette at Sunday, July 14, 2002 23:12:08 Europe/Zurich

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eodistribution.client.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _GPGCompatibilityPrefs_EOArchive_Spanish extends com.webobjects.eoapplication.EOArchive {
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1, _iBHelpConnector2, _iBHelpConnector3;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0;
    com.webobjects.eointerface.swing.EOMatrix _nsMatrix0;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0;
    com.webobjects.eointerface.swing.EOView _nsCustomView0, _nsCustomView1;
    javax.swing.JCheckBox _nsButton0;
    javax.swing.JRadioButton _jRadioButton0, _jRadioButton1, _jRadioButton2, _jRadioButton3, _jRadioButton4;

    public _GPGCompatibilityPrefs_EOArchive_Spanish(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();


        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "warningImageView")) != null)) {
            _nsImageView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOImageView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsImageView0");
        } else {
            _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView1");
        } else {
            _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "optionMatrix.nextFocusableComponent")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Firmas compatibles con PGP 5.x"), "NSButton4");
        }

        _jRadioButton4 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("Preferencias personalizadas"), "");
        _iBHelpConnector3 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jRadioButton3 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("OpenPGP (RFC 2440)"), "");
        _iBHelpConnector2 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jRadioButton2 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("PGP 2.x (MIT PGP 2.6.2)"), "");
        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jRadioButton1 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("PGP 2.x (RFC 1991)"), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "optionMatrix")) != null)) {
            _nsMatrix0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOMatrix)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsMatrix0");
        } else {
            _nsMatrix0 = (com.webobjects.eointerface.swing.EOMatrix)_registered(new com.webobjects.eointerface.swing.EOMatrix(5, 1, 4, 2), "NSMatrix1");
        }

        _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _jRadioButton0 = (javax.swing.JRadioButton)_registered(new javax.swing.JRadioButton("PGP 6"), "");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
    }

    protected void _awaken() {
        super._awaken();
        _jRadioButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "chooseOptionSet", _jRadioButton1), ""));
        _jRadioButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "chooseOptionSet", _jRadioButton2), ""));
        _jRadioButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "chooseOptionSet", _jRadioButton0), ""));
        _jRadioButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "chooseOptionSet", _jRadioButton3), ""));
        _jRadioButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "chooseOptionSet", _jRadioButton4), ""));

        if (_replacedObjects.objectForKey("_nsImageView0") == null) {
            _connect(_owner(), _nsImageView0, "warningImageView");
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "optionMatrix");
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "pgp5Button");
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_owner(), _nsMatrix0, "initialFirstResponder");
        }

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            _connect(_owner(), _nsCustomView1, "view");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "togglePGP5Option", _nsButton0), ""));
    }

    protected void _init() {
        super._init();

        if (_replacedObjects.objectForKey("_nsCustomView1") == null) {
            if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
            _nsCustomView0.setSize(380, 205);
            _nsCustomView0.setLocation(80, 38);
            ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsCustomView0, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin | EOViewLayout.MinYMargin);
            _nsCustomView1.add(_nsCustomView0);
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _connect(_nsMatrix0, _nsButton0, "nextFocusableComponent");
        }

        _setFontForComponent(_jRadioButton4, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton3, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton2, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_jRadioButton1, "Lucida Grande", 13, Font.PLAIN);

        if (_replacedObjects.objectForKey("_nsMatrix0") == null) {
            _jRadioButton1.setSize(344, 17);
            _jRadioButton1.setLocation(0, 0);
            _nsMatrix0.add(_jRadioButton1);
            _jRadioButton2.setSize(344, 17);
            _jRadioButton2.setLocation(0, 19);
            _nsMatrix0.add(_jRadioButton2);
            _jRadioButton0.setSize(344, 17);
            _jRadioButton0.setLocation(0, 38);
            _nsMatrix0.add(_jRadioButton0);
            _jRadioButton3.setSize(344, 17);
            _jRadioButton3.setLocation(0, 57);
            _nsMatrix0.add(_jRadioButton3);
            _jRadioButton4.setSize(344, 17);
            _jRadioButton4.setLocation(0, 76);
            _nsMatrix0.add(_jRadioButton4);
            _setFontForComponent(_nsMatrix0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
        _nsMatrix0.setSize(344, 99);
        _nsMatrix0.setLocation(18, 18);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsMatrix0, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsMatrix0);
        _nsButton0.setSize(344, 17);
        _nsButton0.setLocation(18, 122);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsButton0);
        _nsTextField0.setSize(321, 43);
        _nsTextField0.setLocation(39, 141);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsTextField0);
        _nsImageView0.setSize(16, 16);
        _nsImageView0.setLocation(20, 145);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsImageView0);
        _setFontForComponent(_jRadioButton0, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsTextField0, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("OpenPGP establece que las implementaciones deber\u00edan generar firmas v4, pero PGP 5.x s\u00f3lo reconoce firmas v4 en materia de claves. Esta opci\u00f3n obliga a usar firmas v3 al firmar datos.");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
    }
}
