// _GPGSignaturePrefs_EOArchive_English.java
// Generated by EnterpriseObjects palette at Thursday, June 13, 2002 22:13:11 Europe/Zurich

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eodistribution.client.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _GPGSignaturePrefs_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1;
    com.webobjects.eointerface.swing.EOTextField _nsTextField0, _nsTextField1;
    com.webobjects.eointerface.swing.EOView _nsCustomView0, _nsCustomView1;
    javax.swing.JCheckBox _nsButton0, _nsButton1;

    public _GPGSignaturePrefs_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "commentSwitch")) != null)) {
            _nsButton1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton1");
        } else {
            _nsButton1 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Use comment:"), "NSButton41");
        }

        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsCustomView1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "view")) != null)) {
            _nsCustomView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsCustomView0");
        } else {
            _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "initialFirstResponder.nextFocusableComponent")) != null)) {
            _nsButton0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JCheckBox)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton0");
        } else {
            _nsButton0 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Display Version"), "NSButton4");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "commentSwitch.nextFocusableComponent")) != null)) {
            _nsTextField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField0");
        } else {
            _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }
    }

    protected void _awaken() {
        super._awaken();
        _nsTextField0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "updateComment", _nsTextField0), ""));

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "initialFirstResponder");
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _connect(_owner(), _nsButton0, "versionSwitch");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_owner(), _nsTextField0, "customCommentTextField");
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_owner(), _nsButton1, "commentSwitch");
        }

        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "toggleComment", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            _connect(_owner(), _nsCustomView0, "view");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "toggleVersion", _nsButton0), ""));
    }

    protected void _init() {
        super._init();

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _connect(_nsButton1, _nsTextField0, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsButton1") == null) {
            _setFontForComponent(_nsButton1, "Lucida Grande", 13, Font.PLAIN);
        }

        _setFontForComponent(_nsTextField1, "Lucida Grande", 10, Font.PLAIN);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("The comment and version fields are displayed in armored signatures, as well as in armored encrypted data. For this reason, it should contain only ASCII characters; characters other than ASCII might cause problems in mail signatures.");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        if (!(_nsCustomView1.getLayout() instanceof EOViewLayout)) { _nsCustomView1.setLayout(new EOViewLayout()); }
        _nsButton0.setSize(424, 17);
        _nsButton0.setLocation(18, 46);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsCustomView1.add(_nsButton0);
        _nsTextField1.setSize(420, 112);
        _nsTextField1.setLocation(20, 65);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsTextField1);
        _nsTextField0.setSize(303, 26);
        _nsTextField0.setLocation(137, 11);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.WidthSizable | EOViewLayout.MaxYMargin);
        _nsCustomView1.add(_nsTextField0);
        _nsButton1.setSize(113, 17);
        _nsButton1.setLocation(18, 19);
        ((EOViewLayout)_nsCustomView1.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsCustomView1.add(_nsButton1);

        if (_replacedObjects.objectForKey("_nsCustomView0") == null) {
            if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
            _nsCustomView1.setSize(460, 197);
            _nsCustomView1.setLocation(40, 53);
            ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsCustomView1, EOViewLayout.MinXMargin | EOViewLayout.MaxXMargin | EOViewLayout.MaxYMargin | EOViewLayout.MinYMargin);
            _nsCustomView0.add(_nsCustomView1);
        }

        if (_replacedObjects.objectForKey("_nsButton0") == null) {
            _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _connect(_nsTextField0, _nsButton0, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField0") == null) {
            _setFontForComponent(_nsTextField0, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField0.setEditable(true);
            _nsTextField0.setOpaque(true);
            _nsTextField0.setText("");
            _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField0.setSelectable(true);
            _nsTextField0.setEnabled(true);
        }
    }
}
